IF NOT EXISTS(SELECT * FROM [sys].[objects] WHERE [object_id] = OBJECT_ID(N'[OPERATION_RISK_CONTROL]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[OPERATION_RISK_CONTROL](
	[CONTROL_ID] [uniqueidentifier] NOT NULL CONSTRAINT [PK__OPERATION_RISK_CONTROL__CONTROL_ID] PRIMARY KEY,
	[DOWN_PAYMENT] [decimal](18,4) NULL,
	[DOWN_PAYMENT_RATIO] [decimal](18,10) NULL,
	[TERM] INT NULL,
	[DEALER_ID] INT NULL,
	[STAGE] INT NULL,
	[MAKE_ID] INT NOT NULL,
	[WMR] [bit] NOT NULL,
	[VAP] [bit] NOT NULL,
	[CREATE_TIME] [datetime] NOT NULL,
	[UPDATE_TIME] [datetime] NOT NULL,
	[STATUS] INT NOT NULL
	)
END
GO
